## TESTES SIORG

In [1]:
import os
import boto3
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

bucket = os.environ["S3_BUCKET_NAME"]

s3 = boto3.client(
    "s3",
    region_name=os.getenv("AWS_DEFAULT_REGION", "us-east-1"),
)

rows = []

paginator = s3.get_paginator("list_objects_v2")

for page in paginator.paginate(Bucket=bucket):
    for obj in page.get("Contents", []):
        rows.append({
            "key": obj["Key"],
            "size_bytes": obj["Size"],
            "size_mb": round(obj["Size"] / 1024**2, 2),
            "last_modified": obj["LastModified"],
        })

inventory = pd.DataFrame(rows)

inventory.sort_values("key")

,key,size_bytes,size_mb,last_modified
0,connection_test.txt,103,0.00,2026-07-08 22:29:28+00:00
1,distribuicao/distribuicao-orgaos-siorg-2022-08...,37817938,36.07,2026-07-08 22:55:29+00:00
2,distribuicao/distribuicao-orgaos-siorg-2022-09...,37822278,36.07,2026-07-08 22:55:38+00:00
3,distribuicao/distribuicao-orgaos-siorg-2022-10...,37243700,35.52,2026-07-08 22:55:45+00:00
4,distribuicao/distribuicao-orgaos-siorg-2022-11...,37019763,35.30,2026-07-08 22:55:50+00:00
...,...,...,...,...
94,iceberg/siorg/teste_conexao-bc855a0621844a068a...,3349,0.00,2026-07-13 18:20:49+00:00
95,iceberg/siorg/teste_conexao-bc855a0621844a068a...,550,0.00,2026-07-13 18:20:48+00:00
96,iceberg/siorg/teste_conexao-bc855a0621844a068a...,7081,0.01,2026-07-13 18:20:47+00:00
97,iceberg/siorg/teste_conexao-bc855a0621844a068a...,4492,0.00,2026-07-13 18:20:48+00:00
98,iceberg/siorg/teste_conexao-bc855a0621844a068a...,4313,0.00,2026-07-13 18:19:52+00:00

In [2]:
csv_files = inventory[
    inventory["key"].str.lower().str.endswith(".csv")
].copy()

csv_files

,key,size_bytes,size_mb,last_modified
1,distribuicao/distribuicao-orgaos-siorg-2022-08...,37817938,36.07,2026-07-08 22:55:29+00:00
2,distribuicao/distribuicao-orgaos-siorg-2022-09...,37822278,36.07,2026-07-08 22:55:38+00:00
3,distribuicao/distribuicao-orgaos-siorg-2022-10...,37243700,35.52,2026-07-08 22:55:45+00:00
4,distribuicao/distribuicao-orgaos-siorg-2022-11...,37019763,35.30,2026-07-08 22:55:50+00:00
5,distribuicao/distribuicao-orgaos-siorg-2022-12...,37125186,35.41,2026-07-08 22:55:53+00:00
...,...,...,...,...
87,estrutura-organizacional-completa/estrutura-or...,150697279,143.72,2026-07-08 22:54:22+00:00
88,estrutura-organizacional-completa/estrutura-or...,151472277,144.46,2026-07-08 22:54:31+00:00
89,estrutura-organizacional-completa/estrutura-or...,153268351,146.17,2026-07-08 22:54:42+00:00
90,estrutura-organizacional-completa/estrutura-or...,154224777,147.08,2026-07-08 22:54:54+00:00
91,estrutura-organizacional-completa/estrutura-or...,154688853,147.52,2026-07-08 22:55:08+00:00

In [3]:
csv_files["prefixo"] = csv_files["key"].str.split("/").str[0]

resumo_prefixos = (
    csv_files
    .groupby("prefixo")
    .agg(
        arquivos=("key", "count"),
        tamanho_total_gb=("size_bytes", lambda x: round(x.sum() / 1024**3, 2)),
        tamanho_medio_mb=("size_mb", "mean"),
        menor_arquivo_mb=("size_mb", "min"),
        maior_arquivo_mb=("size_mb", "max"),
    )
    .reset_index()
)

resumo_prefixos

,prefixo,arquivos,tamanho_total_gb,tamanho_medio_mb,menor_arquivo_mb,maior_arquivo_mb
0,distribuicao,45,1.66,37.764444,35.30,40.69
1,estrutura-organizacional-completa,46,5.90,131.328043,112.29,147.52

In [4]:
pd.set_option("display.max_colwidth", None)

for prefixo in csv_files["prefixo"].unique():
    print(f"\n### {prefixo}")
    display(
        csv_files[csv_files["prefixo"] == prefixo][
            ["key", "size_mb"]
        ].sort_values("key")
    )

### distribuicao

                                                   key  size_mb
1   distribuicao/distribuicao-orgaos-siorg-2022-08.csv    36.07
2   distribuicao/distribuicao-orgaos-siorg-2022-09.csv    36.07
3   distribuicao/distribuicao-orgaos-siorg-2022-10.csv    35.52
4   distribuicao/distribuicao-orgaos-siorg-2022-11.csv    35.30
5   distribuicao/distribuicao-orgaos-siorg-2022-12.csv    35.41
6   distribuicao/distribuicao-orgaos-siorg-2023-01.csv    35.42
7   distribuicao/distribuicao-orgaos-siorg-2023-02.csv    35.30
8   distribuicao/distribuicao-orgaos-siorg-2023-03.csv    35.30
9   distribuicao/distribuicao-orgaos-siorg-2023-04.csv    35.30
10  distribuicao/distribuicao-orgaos-siorg-2023-05.csv    35.33
11  distribuicao/distribuicao-orgaos-siorg-2023-06.csv    35.32
12  distribuicao/distribuicao-orgaos-siorg-2023-07.csv    37.59
13  distribuicao/distribuicao-orgaos-siorg-2023-08.csv    37.58
14  distribuicao/distribuicao-orgaos-siorg-2023-09.csv    37.58
15  distribuicao/distribuicao-orgaos-siorg-2023-10.csv    37.57
16  distribuicao/distribuicao-orgaos-siorg-2023-11.csv    37.81
17  distribuicao/distribuicao-orgaos-siorg-2023-12.csv    37.86
18  distribuicao/distribuicao-orgaos-siorg-2024-01.csv    37.88
19  distribuicao/distribuicao-orgaos-siorg-2024-03.csv    38.02
20  distribuicao/distribuicao-orgaos-siorg-2024-04.csv    37.63
21  distribuicao/distribuicao-orgaos-siorg-2024-05.csv    37.63
22  distribuicao/distribuicao-orgaos-siorg-2024-06.csv    37.74
23  distribuicao/distribuicao-orgaos-siorg-2024-07.csv    37.78
24  distribuicao/distribuicao-orgaos-siorg-2024-09.csv    37.84
25  distribuicao/distribuicao-orgaos-siorg-2024-10.csv    37.96
26  distribuicao/distribuicao-orgaos-siorg-2024-11.csv    38.04
27  distribuicao/distribuicao-orgaos-siorg-2024-12.csv    38.11
28  distribuicao/distribuicao-orgaos-siorg-2025-01.csv    38.17
29  distribuicao/distribuicao-orgaos-siorg-2025-02.csv    38.15
30  distribuicao/distribuicao-orgaos-siorg-2025-03.csv    38.16
31  distribuicao/distribuicao-orgaos-siorg-2025-04.csv    38.16
32  distribuicao/distribuicao-orgaos-siorg-2025-05.csv    38.17
33  distribuicao/distribuicao-orgaos-siorg-2025-06.csv    38.19
34  distribuicao/distribuicao-orgaos-siorg-2025-07.csv    38.33
35  distribuicao/distribuicao-orgaos-siorg-2025-08.csv    38.47
36  distribuicao/distribuicao-orgaos-siorg-2025-10.csv    38.64
37  distribuicao/distribuicao-orgaos-siorg-2025-11.csv    38.97
38  distribuicao/distribuicao-orgaos-siorg-2025-12.csv    39.02
39  distribuicao/distribuicao-orgaos-siorg-2026-01.csv    40.14
40  distribuicao/distribuicao-orgaos-siorg-2026-02.csv    40.15
41  distribuicao/distribuicao-orgaos-siorg-2026-03.csv    40.13
42  distribuicao/distribuicao-orgaos-siorg-2026-04.csv    40.12
43  distribuicao/distribuicao-orgaos-siorg-2026-05.csv    40.21
44  distribuicao/distribuicao-orgaos-siorg-2026-06.csv    40.57
45  distribuicao/distribuicao-orgaos-siorg-2026-07.csv    40.69

### estrutura-organizacional-completa

,key,size_mb
46,estrutura-organizacional-completa/estrutura-organizacional-completa-2022-08.csv,112.29
47,estrutura-organizacional-completa/estrutura-organizacional-completa-2022-09.csv,112.39
48,estrutura-organizacional-completa/estrutura-organizacional-completa-2022-10.csv,113.64
49,estrutura-organizacional-completa/estrutura-organizacional-completa-2022-11.csv,123.40
50,estrutura-organizacional-completa/estrutura-organizacional-completa-2022-12.csv,123.40
51,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-01.csv,123.40
52,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-02.csv,123.40
53,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-03.csv,123.40
54,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-04.csv,123.40
55,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-05.csv,123.57
56,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-06.csv,123.93
57,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-07.csv,123.96
58,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-08.csv,124.57
59,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-09.csv,125.00
60,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-10.csv,125.19
61,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-11.csv,127.08
62,estrutura-organizacional-completa/estrutura-organizacional-completa-2023-12.csv,127.76
63,estrutura-organizacional-completa/estrutura-organizacional-completa-2024-01.csv,128.02
64,estrutura-organizacional-completa/estrutura-organizacional-completa-2024-02.csv,129.16
65,estrutura-organizacional-completa/estrutura-organizacional-completa-2024-03.csv,129.36
66,estrutura-organizacional-completa/estrutura-organizacional-completa-2024-04.csv,129.50
67,estrutura-organizacional-completa/estrutura-organizacional-completa-2024-05.csv,130.20
68,estrutura-organizacional-completa/estrutura-organizacional-completa-2024-06.csv,130.94
69,estrutura-organizacional-completa/estrutura-organizacional-completa-2024-07.csv,131.44
70,estrutura-organizacional-completa/estrutura-organizacional-completa-2024-09.csv,132.26
71,estrutura-organizacional-completa/estrutura-organizacional-completa-2024-10.csv,132.32
72,estrutura-organizacional-completa/estrutura-organizacional-completa-2024-11.csv,132.86
73,estrutura-organizacional-completa/estrutura-organizacional-completa-2024-12.csv,133.37
74,estrutura-organizacional-completa/estrutura-organizacional-completa-2025-01.csv,133.91
75,estrutura-organizacional-completa/estrutura-organizacional-completa-2025-02.csv,134.87
76,estrutura-organizacional-completa/estrutura-organizacional-completa-2025-03.csv,135.22
77,estrutura-organizacional-completa/estrutura-organizacional-completa-2025-04.csv,135.59
78,estrutura-organizacional-completa/estrutura-organizacional-completa-2025-05.csv,136.15
79,estrutura-organizacional-completa/estrutura-organizacional-completa-2025-06.csv,136.41
80,estrutura-organizacional-completa/estrutura-organizacional-completa-2025-07.csv,136.62
81,estrutura-organizacional-completa/estrutura-organizacional-completa-2025-08.csv,139.30
82,estrutura-organizacional-completa/estrutura-organizacional-completa-2025-10.csv,139.39
83,estrutura-organizacional-completa/estrutura-organizacional-completa-2025-11.csv,139.49
84,estrutura-organizacional-completa/estrutura-organizacional-completa-2025-12.csv,140.59
85,estrutura-organizacional-completa/estrutura-organizacional-completa-2026-01.csv,142.20
86,estrutura-organizacional-completa/estrutura-organizacional-completa-2026-02.csv,143.19
87,estrutura-organizacional-completa/estrutura-organizacional-completa-2026-03.csv,143.72
88,estrutura-organizacional-completa/estrutura-organizacional-completa-2026-04.csv,144.46
89,estrutura-organizacional-completa/estrutura-organizacional-completa-2026-05.csv,146.17
90,estrutura-organizacional-completa/estrutura-organizacional-completa-2026-06.csv,147.08
91,estrutura-organizacional-completa/estrutura-organizacional-completa-2026-07.csv,147.52

In [5]:
import io
import pandas as pd

def ler_amostra_s3(key, linhas=10):
    obj = s3.get_object(
        Bucket=bucket,
        Key=key,
    )

    raw = obj["Body"].read(5_000_000)

    for encoding in ["utf-8-sig", "utf-8", "latin-1"]:
        try:
            texto = raw.decode(encoding)

            df = pd.read_csv(
                io.StringIO(texto),
                sep=None,
                engine="python",
                nrows=linhas,
            )

            return df, encoding

        except Exception:
            continue

    raise ValueError(f"Não foi possível ler {key}")

In [6]:
amostras = {}

for prefixo in csv_files["prefixo"].unique():
    key = (
        csv_files[csv_files["prefixo"] == prefixo]
        .sort_values("key")
        .iloc[0]["key"]
    )

    df, encoding = ler_amostra_s3(key)

    amostras[prefixo] = df

    print(f"\n### {prefixo}")
    print(f"Arquivo: {key}")
    print(f"Encoding: {encoding}")
    print(f"Colunas: {list(df.columns)}")

    display(df.head())

### distribuicao
Arquivo: distribuicao/distribuicao-orgaos-siorg-2022-08.csv
Encoding: utf-8-sig
Colunas: ['nivel_hierarquico', 'cod_orgao_entidade', 'nome_orgao_entidade', 'sigla_orgao_entidade', 'natureza_juridica', 'subnatureza_juridica', 'poder', 'esfera', 'cod_unidade_pai', 'cod_unidade', 'nome_unidade', 'sigla_unidade', 'endereco', 'endereco_complemento', 'bairro', 'municipio', 'uf', 'cep', 'telefone', 'email', 'area_atuacao', 'nivel_normatizacao', 'autonomia_gestao_cargos', 'tipo_cargo', 'categoria_cargo', 'nivel_cargo', 'denominacao_cargo', 'complemento_denominacao', 'mobilidade', 'obriga_distribuicao', 'compoe_estrutura', 'autoridade', 'regra_autoridade', 'regra_cargo_nome_unidade', 'temporario', 'cod_instancia']

,nivel_hierarquico,cod_orgao_entidade,nome_orgao_entidade,sigla_orgao_entidade,natureza_juridica,subnatureza_juridica,poder,esfera,cod_unidade_pai,cod_unidade,...,denominacao_cargo,complemento_denominacao,mobilidade,obriga_distribuicao,compoe_estrutura,autoridade,regra_autoridade,regra_cargo_nome_unidade,temporario,cod_instancia
0,1,200000,República Federativa do Brasil,,NaN,NaN,NaN,NaN,NaN,200000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,208614,Distrito Federal,DF,NaN,NaN,NaN,Estadual/Distrital,200000.0,208614,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,208615,Poder Executivo,PE,NaN,NaN,Executivo,Estadual/Distrital,208614.0,208615,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,200002,Governo do Distrito Federal,GDF,Administração Direta,NaN,Executivo,Estadual/Distrital,208615.0,200002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,266982,Polícia Civil do Distrito Federal,PCDF,Administração Direta,NaN,Executivo,Estadual/Distrital,200002.0,266982,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### estrutura-organizacional-completa
Arquivo: estrutura-organizacional-completa/estrutura-organizacional-completa-2022-08.csv
Encoding: utf-8-sig
Colunas: ['codigoUnidade', 'codigoUnidadePai', 'codigoOrgaoEntidade', 'codigoTipoUnidade', 'nome', 'sigla', 'codigoEsfera', 'codigoPoder', 'codigoNaturezaJuridica', 'codigoSubNaturezaJuridica', 'nivelNormatizacao', 'versaoConsulta', 'dataInicialVersaoConsulta', 'dataFinalVersaoConsulta', 'operacao', 'codigoUnidadePaiAnterior', 'codigoOrgaoEntidadeAnterior', 'regulamentoEspecifico', 'codigoCategoriaUnidade', 'competencia', 'finalidade', 'missao', 'descricaoAtoNormativo', 'areaAtuacao', 'telefone', 'email', 'site', 'linhaEndereco', 'bairro', 'cep', 'uf', 'municipio', 'pais', 'horarioFuncionamento']

,codigoUnidade,codigoUnidadePai,codigoOrgaoEntidade,codigoTipoUnidade,nome,sigla,codigoEsfera,codigoPoder,codigoNaturezaJuridica,codigoSubNaturezaJuridica,...,telefone,email,site,linhaEndereco,bairro,cep,uf,municipio,pais,horarioFuncionamento
0,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/200000,NaN,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/200000,http://estruturaorganizacional.dados.gov.br/id/tipo-unidade/ente,República Federativa do Brasil,,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/200001,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/200000,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/200001,http://estruturaorganizacional.dados.gov.br/id/tipo-unidade/ente,União,UNIAO,http://estruturaorganizacional.dados.gov.br/id/esfera/1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/200002,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/208615,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/200002,http://estruturaorganizacional.dados.gov.br/id/tipo-unidade/orgao,Governo do Distrito Federal,GDF,http://estruturaorganizacional.dados.gov.br/id/esfera/2,http://estruturaorganizacional.dados.gov.br/id/poder/1,http://estruturaorganizacional.dados.gov.br/id/natureza-juridica/3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/36554,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/1,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/1,http://estruturaorganizacional.dados.gov.br/id/tipo-unidade/unidade-colegiada,Fundo Nacional de Desenvolvimento Científico e Tecnológico,FNDCT,http://estruturaorganizacional.dados.gov.br/id/esfera/1,http://estruturaorganizacional.dados.gov.br/id/poder/1,http://estruturaorganizacional.dados.gov.br/id/natureza-juridica/1,NaN,...,(55) (21) 25550330,presidencia@finep.gov.br,www.finep.gov.br,"Av. República do Chile, 330, Torre Oeste , 10º, 11º, 12º, 15º, 16º e 17º andares",Centro,20031170.0,RJ,3304557.0,NaN,NaN
4,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/84172,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/1,http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/1,http://estruturaorganizacional.dados.gov.br/id/tipo-unidade/unidade-colegiada,Conselho Consultivo,CC-FINEP,http://estruturaorganizacional.dados.gov.br/id/esfera/1,http://estruturaorganizacional.dados.gov.br/id/poder/1,http://estruturaorganizacional.dados.gov.br/id/natureza-juridica/1,NaN,...,(55) (21) 25550330,presidencia@finep.gov.br,www.finep.gov.br,"Av. República do Chile, 330, Torre Oeste , 10º, 11º, 12º, 15º, 16º e 17º andares",Centro,20031170.0,RJ,3304557.0,NaN,NaN

In [7]:
for prefixo, df in amostras.items():
    print(f"\n### Perfil: {prefixo}")

    perfil = pd.DataFrame({
        "coluna": df.columns,
        "tipo_pandas": df.dtypes.astype(str).values,
        "nulos_amostra": df.isna().sum().values,
        "distintos_amostra": df.nunique(dropna=True).values,
    })

    display(perfil)

### Perfil: distribuicao

                      coluna tipo_pandas  nulos_amostra  distintos_amostra
0          nivel_hierarquico       int64              0                  8
1         cod_orgao_entidade       int64              0                  5
2        nome_orgao_entidade      object              0                  5
3       sigla_orgao_entidade      object              0                  5
4          natureza_juridica      object              3                  1
5       subnatureza_juridica     float64             10                  0
6                      poder      object              2                  1
7                     esfera      object              1                  1
8            cod_unidade_pai     float64              1                  7
9                cod_unidade       int64              0                 10
10              nome_unidade      object              0                 10
11             sigla_unidade      object              0                 10
12                  endereco      object              4                  3
13      endereco_complemento      object              4                  2
14                    bairro      object              4                  2
15                 municipio      object              4                  1
16                        uf      object              4                  1
17                       cep     float64              4                  1
18                  telefone     float64              4                  4
19                     email      object              4                  6
20              area_atuacao      object              6                  1
21        nivel_normatizacao      object              0                  2
22   autonomia_gestao_cargos      object              0                  1
23                tipo_cargo     float64             10                  0
24           categoria_cargo     float64             10                  0
25               nivel_cargo     float64             10                  0
26         denominacao_cargo     float64             10                  0
27   complemento_denominacao     float64             10                  0
28                mobilidade     float64             10                  0
29       obriga_distribuicao     float64             10                  0
30          compoe_estrutura     float64             10                  0
31                autoridade     float64             10                  0
32          regra_autoridade     float64             10                  0
33  regra_cargo_nome_unidade     float64             10                  0
34                temporario     float64             10                  0
35             cod_instancia     float64             10                  0

### Perfil: estrutura-organizacional-completa

                         coluna tipo_pandas  nulos_amostra  distintos_amostra
0                 codigoUnidade      object              0                 10
1              codigoUnidadePai      object              1                  5
2           codigoOrgaoEntidade      object              0                  4
3             codigoTipoUnidade      object              0                  5
4                          nome      object              0                 10
5                         sigla      object              0                  9
6                  codigoEsfera      object              1                  2
7                   codigoPoder      object              2                  1
8        codigoNaturezaJuridica      object              2                  2
9     codigoSubNaturezaJuridica     float64             10                  0
10            nivelNormatizacao      object              0                  2
11               versaoConsulta      object              0                  2
12    dataInicialVersaoConsulta      object              0                  2
13      dataFinalVersaoConsulta     float64             10                  0
14                     operacao     float64             10                  0
15     codigoUnidadePaiAnterior     float64             10                  0
16  codigoOrgaoEntidadeAnterior     float64             10                  0
17        regulamentoEspecifico      object              8                  1
18       codigoCategoriaUnidade      object              2                  4
19                  competencia      object              7                  3
20                   finalidade      object              8                  2
21                       missao     float64             10                  0
22        descricaoAtoNormativo      object              8                  2
23                  areaAtuacao     float64             10                  0
24                     telefone      object              3                  1
25                        email      object              3                  1
26                         site      object              3                  1
27                linhaEndereco      object              3                  1
28                       bairro      object              3                  1
29                          cep     float64              3                  1
30                           uf      object              3                  1
31                    municipio     float64              3                  1
32                         pais     float64             10                  0
33         horarioFuncionamento     float64             10                  0